application: reservationmaster
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /
  script: mainpage.app
  
- url: /create_resource.*
  script: create_resource.app
  login: required
  
- url: /resource.*
  script: resource.app
  
- url: /user.*
  script: user.app

- url: /tag.*
  script: tag.app

- url: /rss.*
  script: rss.app
  
- url: /.*
  script: error.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
